import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { paddingBottom: 24 },
  center: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  heroWrapper: {
    marginHorizontal: 12,
    marginTop: 12,
    borderRadius: 18,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOpacity: 0.18,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  heroImage: { width: '100%', height: 240 },
  title: {
    fontSize: 24,
    fontWeight: '800',
    marginTop: 16,
    paddingHorizontal: 16,
  },
  location: {
    fontSize: 14,
    color: '#64748b',
    paddingHorizontal: 16,
    marginTop: 4,
  },
  meta: {
    fontSize: 13,
    color: '#94a3b8',
    paddingHorizontal: 16,
    marginTop: 4,
  },
  price: {
    fontSize: 16,
    color: '#16a34a',
    fontWeight: '700',
    paddingHorizontal: 16,
    marginTop: 8,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    marginTop: 20,
    marginBottom: 6,
    paddingHorizontal: 16,
  },
  paragraph: {
    fontSize: 14,
    color: '#334155',
    paddingHorizontal: 16,
    marginBottom: 6,
  },
  chipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    paddingHorizontal: 16,
    marginBottom: 10,
    marginTop: 4,
  },
  chip: {
    borderRadius: 999,
    backgroundColor: '#e0f2fe',
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  chipText: { fontSize: 12, color: '#0f172a' },
  tourCard: {
    backgroundColor: '#fff',
    borderRadius: 14,
    padding: 12,
    marginHorizontal: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
    elevation: 1,
  },
  tourTitle: { fontSize: 15, fontWeight: '700', marginBottom: 4 },
  tourPrice: { fontSize: 13, fontWeight: '600', color: '#16a34a' },
  primaryButton: {
    marginTop: 16,
    marginHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 999,
    backgroundColor: '#0f766e',
    alignItems: 'center',
  },
  primaryButtonText: { color: '#fff', fontWeight: '700' },
  secondaryButton: {
    marginTop: 8,
    marginHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: '#e2e8f0',
    alignItems: 'center',
    marginBottom: 24,
  },
  secondaryButtonText: { color: '#0f172a', fontWeight: '600' },
  summaryBox: {
    marginHorizontal: 16,
    marginTop: 12,
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    backgroundColor: '#eff6ff',
  },
  summaryTitle: {
    fontSize: 14,
    fontWeight: '700',
    marginBottom: 4,
    color: '#0f172a',
  },
  summaryItem: {
    fontSize: 13,
    color: '#475569',
  },
  selectedPlanBox: {
    marginHorizontal: 16,
    marginTop: 16,
    marginBottom: 8,
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
  },
  selectedTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: '#64748b',
    marginBottom: 4,
  },
  selectedName: {
    fontSize: 16,
    fontWeight: '700',
    color: '#0f172a',
  },
  selectedMeta: {
    fontSize: 13,
    color: '#64748b',
    marginTop: 2,
  },
  selectedPrice: {
    fontSize: 14,
    fontWeight: '700',
    color: '#16a34a',
    marginTop: 4,
  },
  backButton: {
    marginTop: 12,
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderWidth: 1,
    borderRadius: 999,
  },
  backButtonText: { fontWeight: '600' },
});
